version: '3.3'

services: 
  web:
    build: ./
    image: nodejs
    ports:
      - "5000:5000"
    volumes:
      - .:/home/node/app
    env_file: .env
    environment:
      - GMAIL_USER=$GMAIL_USER
      - GMAIL_PASSWORD=$GMAIL_PASSWORD}
    depends_on:
      - mongo
    command: npm start
  mongo:
    image: mongo
    ports:
        - '27017:27017'
    env_file: .env
    environment: 
      - MONGO_USER=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_PATH=$MONGO_PATH
    volumes:
      - .:/home/db
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - '8080:8080'
    environment: 
      - API_URL=http://localhost:5000/rest
    depends_on:
      - web
volumes:
  data-volume:
