version: '3.3'

services: 
  backend-app:
    build: ./
    image: nodejs
    ports:
      - "5000:5000"
    volumes:
      - .:/home/node/app
    # depends_on:
    #   - db
    env_file: .env
    environment:
      - GMAIL_USER=$GMAIL_USER
      - GMAIL_PASSWORD=$GMAIL_PASSWORD}
    command: npm start
#   db:
#     image: mongo
#     ports:
#         - '27017:27017'
#     env_file: .env
#     environment: 
#       - MONGO_USER=$MONGO_USER
#       - MONGO_PASSWORD=$MONGO_PASSWORD
#       - MONGO_PATH=$MONGO_PATH
#     volumes:
#       - data-volume:/data/db
# volumes:
#   data-volume: